---
- name: 'Configure and start MySQL Exporter'
  become: true
  block:
    - name: 'Configure SystemD unit for MySQL Exporter'
      ansible.builtin.template:
        src: 'mysqld_exporter.service.j2'
        dest: '/etc/systemd/system/mysqld_exporter.service'
        owner: '{{ mysqld_exporter_user }}'
        group: '{{ mysqld_exporter_group }}'
        mode: 0644
      register: _mysqld_exporter_service

    - name: 'Reload systemd daemon if unit file is changed'
      ansible.builtin.systemd:
        daemon_reload: true
      when: _mysqld_exporter_service is changed
      notify: Restart MySQL Exporter

    - name: 'Configure .cnf file for MySQL Exporter'
      ansible.builtin.template:
        src: 'mysqld_exporter.cnf.j2'
        dest: '{{ mysqld_exporter_config_path }}/.mysqld_exporter.cnf'
        owner: '{{ mysqld_exporter_user }}'
        group: '{{ mysqld_exporter_group }}'
        mode: 0600
      notify: Restart MySQL Exporter

    - name: 'Ensure MySQL Exporter is running and enabled at boot'
      ansible.builtin.systemd:
        name: mysqld_exporter
        state: started
        enabled: true
