---
- name: 'Check if MySQL Exporter is installed'
  ansible.builtin.stat:
    path: '{{ mysqld_exporter_install_path }}/mysqld_exporter'
  register: __mysqld_exporter_is_installed

- name: 'Check the current MySQL Exporter version'
  ansible.builtin.command:
    cmd: '{{ mysqld_exporter_install_path }}/mysqld_exporter --version'
  failed_when: false
  changed_when: false
  register: __mysqld_exporter_version_check

- name: 'Download and unarchive the MySQL Exporter'
  when:
    - not __mysqld_exporter_is_installed.stat.exists or
      ( __mysqld_exporter_version_check.stderr_lines | length and
      mysqld_exporter_version not in __mysqld_exporter_version_check.stderr_lines[0].split()[2] ) or
      ( __mysqld_exporter_version_check.stdout_lines | length and
      mysqld_exporter_version not in __mysqld_exporter_version_check.stdout_lines[0].split()[2] )
  block:
    - name: 'Download the MySQL Exporter binary to a local folder'
      ansible.builtin.get_url:
        url: '{{ mysqld_exporter_download_url }}/{{ mysqld_exporter_archive_name }}.{{ mysqld_exporter_archive_extension }}'
        dest: '/tmp/{{ mysqld_exporter_archive_name }}.{{ mysqld_exporter_archive_extension }}'
        mode: 0644
      delegate_to: localhost
      check_mode: false

    - name: 'Unarchive the MySQL Exporter binary'
      ansible.builtin.unarchive:
        src: '/tmp/{{ mysqld_exporter_archive_name }}.{{ mysqld_exporter_archive_extension }}'
        dest: '/tmp'
        creates: '/tmp/{{ mysqld_exporter_archive_name }}/mysqld_exporter'
      delegate_to: localhost
      check_mode: false

    - name: 'Copy the MySQL Exporter binary into a place'
      ansible.builtin.copy:
        src: '/tmp/{{ mysqld_exporter_archive_name }}/mysqld_exporter'
        dest: '{{ mysqld_exporter_install_path }}/mysqld_exporter'
        owner: '{{ mysqld_exporter_user }}'
        group: '{{ mysqld_exporter_group }}'
        mode: 0755
      notify: 'Restart the MySQL Exporter'
      when: not ansible_check_mode
      become: true
