---
- name: 'Check that required string variables are defined'
  ansible.builtin.assert:
    that: '{{ required_vars }} is defined and {{ required_vars }}'
    fail_msg: '{{ required_vars }} needs to be set for the role to work'
    success_msg: 'Required variables {{ required_vars }} is defined'
  loop:
    - mysqld_exporter_mysqld_user
    - mysqld_exporter_mysqld_password
  loop_control:
    loop_var: required_vars
  when: mysqld_exporter_setup in ['install','upgrade']

- name: 'Prepare for installing the MySQLd Exporter'
  ansible.builtin.import_tasks: 'pre-install.yml'
  when: mysqld_exporter_setup in ['install','upgrade']

- name: 'Install the MySQLd Exporter'
  ansible.builtin.import_tasks: 'install.yml'
  when: mysqld_exporter_setup in ['install','upgrade']

- name: 'Configure the MySQLd Exporter'
  ansible.builtin.import_tasks: 'configure.yml'
  when: mysqld_exporter_setup in ['install','upgrade']

- name: 'Uninstall the MySQLd Exporter'
  ansible.builtin.import_tasks: 'uninstall.yml'
  when: mysqld_exporter_setup in ['uninstall']
