---
- name: 'Check that mysqld_exporter_mysqld_user variable value are not empty'
  ansible.builtin.assert:
    that: '{{ mysqld_exporter_mysqld_user | length > 0 }}'
    fail_msg: 'mysqld_exporter_mysqld_user needs to be set for the role to work'
    success_msg: 'Required variable mysqld_exporter_mysqld_user is defined'
  when: mysqld_exporter_setup in [ 'install', 'upgrade' ]

- name: 'Check that mysqld_exporter_mysqld_password variable value are not empty'
  ansible.builtin.assert:
    that: '{{ mysqld_exporter_mysqld_password | length > 0 }}'
    fail_msg: 'mysqld_exporter_mysqld_password needs to be set for the role to work'
    success_msg: 'Required variable mysqld_exporter_mysqld_password is defined'
  when: mysqld_exporter_setup in [ 'install', 'upgrade' ]

- name: 'Prepare for installing the MySQLd Exporter'
  ansible.builtin.import_tasks: 'pre-install.yml'
  when: mysqld_exporter_setup in [ 'install', 'upgrade' ]

- name: 'Install the MySQLd Exporter'
  ansible.builtin.import_tasks: 'install.yml'
  when: mysqld_exporter_setup in [ 'install', 'upgrade' ]

- name: 'Configure the MySQLd Exporter'
  ansible.builtin.import_tasks: 'configure.yml'
  when: mysqld_exporter_setup in [ 'install', 'upgrade' ]

- name: 'Uninstall the MySQLd Exporter'
  ansible.builtin.import_tasks: 'uninstall.yml'
  when: mysqld_exporter_setup in [ 'uninstall' ]
