---
- name: 'Check that required string variables are defined'
  ansible.builtin.assert:
    that: '{{ required_vars }} is defined and {{ required_vars }}'
    fail_msg: '{{ required_vars }} needs to be set for the role to work'
    success_msg: 'Required variables {{ required_vars }} is defined'
  loop:
    - mysqld_exporter_mysql_user
    - mysqld_exporter_mysql_password
  loop_control:
    loop_var: required_vars

- name: 'Include tasks to prepare to install MySQL Exporter'
  ansible.builtin.import_tasks: 'pre-install.yml'

- name: 'Include tasks to install MySQL Exporter'
  ansible.builtin.import_tasks: 'install.yml'

- name: 'Include tasks to configure MySQL Exporter'
  ansible.builtin.import_tasks: 'configure.yml'
