---
- name: 'Prepare to install MySQL Exporter'
  become: true
  block:
    - name: 'Create MySQL Exporter group'
      ansible.builtin.group:
        name: '{{ mysqld_exporter_group }}'
        system: true
      become: true

    - name: 'Create MySQL Exporter user'
      ansible.builtin.user:
        name: '{{ mysqld_exporter_user }}'
        group: '{{ mysqld_exporter_group }}'
        comment: 'MySQL Exporter'
        system: true
        createhome: false
        shell: '/bin/false'
