---
- name: 'Prepare to install the MySQLd Exporter'
  become: true
  block:
    - name: 'Create a MySQLd Exporter group'
      ansible.builtin.group:
        name: '{{ mysqld_exporter_group }}'
        system: true

    - name: 'Create a MySQLd Exporter user'
      ansible.builtin.user:
        name: '{{ mysqld_exporter_user }}'
        group: '{{ mysqld_exporter_group }}'
        comment: 'MySQL Exporter'
        system: true
        createhome: false
        shell: '/bin/false'
