---
- name: 'Restart the MySQLd Exporter'
  become: true
  ansible.builtin.systemd:
    name: 'mysqld_exporter'
    daemon_reload: true
    state: 'restarted'
  when: not ansible_check_mode

- name: 'Systemd daemon-reload'
  ansible.builtin.systemd:
    daemon_reload: true
  when: not ansible_check_mode
