---
- name: 'Prepare an Ansible host for Github Actions'
  hosts: localhost
  tasks:
    - name: 'Install tar for delegated to localhost tasks'
      apk:
        name: tar
        update_cache: true
      when: ansible_os_family == 'Alpine'

- name: 'Converge'
  hosts: all
  vars:
    mysqld_exporter_mysql_user: 'exporter'
    mysqld_exporter_mysql_password: 'Pa$$word'
    mysqld_exporter_tls_server_config:
      cert_file: '/usr/local/etc/ssl/mysqld_exporter.cert'
      key_file: '/usr/local/etc/ssl/mysqld_exporter.key'
    mysqld_exporter_basic_auth_users:
      newuser1: newpassword1

  pre_tasks:
    - name: 'Create certificate directories'
      ansible.builtin.file:
        path: '{{ mysqld_exporter_tls_server_config.cert_file | dirname }}'
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: 'Copy certificate and key'
      ansible.builtin.copy:
        src: '{{ cert.src }}'
        dest: '{{ cert.dest }}'
        mode: 0644
        remote_src: true
      loop:
        - src: '/tmp/certificate.cert'
          dest: '{{ mysqld_exporter_tls_server_config.cert_file }}'
        - src: '/tmp/certificate.key'
          dest: '{{ mysqld_exporter_tls_server_config.key_file }}'
      loop_control:
        loop_var: cert

  roles:
    - role: antmelekhin.mysqld_exporter
