---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that MySQLd Exporter service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['mysqld_exporter.service'].state == 'running'
          - ansible_facts.services['mysqld_exporter.service'].status == 'enabled'

    - name: 'Verify the MySQLd Exporter is responding to requests'
      ansible.builtin.uri:
        url: 'https://{{ ansible_host }}:9104/metrics'
        user: 'newuser1'
        password: 'newpassword1'
        force_basic_auth: true
        validate_certs: false
      register: __mysqld_exporter_response
      until: __mysqld_exporter_response.status == 200
      retries: 120
      delay: 5
