---
dependency:
  name: galaxy
  enabled: true
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: instance
    image: 'geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest'
    command: "${MOLECULE_DOCKER_COMMAND:-'/lib/systemd/systemd'}"
    published_ports:
      - 0.0.0.0:9104:9104/udp
      - 0.0.0.0:9104:9104/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
